[plugin]
repository = "https://github.com/dohwadev/Accountant.git"
commit = "ecc4bf8a1f90cadf199d65cac9860937022f2fcf"
owners = [
    "Ottermandias",
		"dohwadev",
]
project_path = "Accountant"
changelog = "Updated for Dalamud staging."
