[plugin]
repository = "https://github.com/dohwadev/Accountant.git"
commit = "1282c693d581ed967cca643c1fae9051a688d80c"
owners = [
    "Ottermandias",
		"dohwadev",
]
project_path = "Accountant"
changelog = "Updated for Dalamud staging."
