name: PAC periodic notification

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * *'

jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dohwacorp/PAC-Nag@1a7de7a622578322019db831d525d4c5f3c53cca
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          discord_webhook: ${{secrets.PAC_DISCORD_WEBHOOK}}
          pacsheetslink: ${{secrets.PAC_SHEETS_LINK}}
